alias apache_restart="sudo systemctl restart apache2"
alias apache_status="sudo systemctl status apache2"
alias vhosts="sudo vim /etc/apache2/sites-enabled"
alias mysql_conf="sudo vim /etc/mysql/mysql.conf.d/mysqld.cnf"
alias mysql_restart="sudo service mysql restart"
